const mediaData = [
  {
    index: 0,
    name: "Dil",
    source: "dil",
    artist: "Kaushik-Guddu",
    type: "bollywood",
    album: "Dil(From Ek The Villian)",
  },
  {
    index: 1,
    name: "Ishq Wala Love",
    source: "ishq_wala_love",
    artist: "Vishal-Shekhar",
    type: "bollywood",
    album: "Student of the year",
  },
  {
    index: 2,
    name: "Toota Jo Kabhi Tara",
    source: "toota_jo_tara",
    artist: "Atif Aslam",
    type: "bollywood",
  },
  {
    index: 3,
    name: "Sanam re",
    source: "sanam_re",
    artist: "Arijith Singh",
    type: "bollywood",
    album: "Sanam Re",
  },
  {
    index: 4,
    name: "Sun Sathiya",
    source: "sun_sathiya",
    artist: "Sachin Jigar",
    type: "bollywood",
    album: "ABCD2",
  },

  {
    index: 5,
    name: "Wajah tum Ho",
    source: "wajah_tum_ho",
    artist: "Armaan Malik",
    type: "bollywood",
    album: "Hate Story 3",
  },
  {
    index: 6,
    name: "Faded",
    source: "faded",
    artist: "Alan Walker",
    type: "hollywood",
    album: "Different World",
  },
  {
    index: 7,
    name: "Despacito",
    source: "despacito",
    artist: "Luis Fonsi",
    type: "hollywood",
    album: "VIDA",
  },
  {
    index: 8,
    name: "MockingBird",
    source: "mockingBird",
    artist: "Eminem",
    type: "hollywood",
    album: "Encore(Deluxe version)",
  },
  {
    index: 9,
    name: "Calm Down",
    source: "calm_down",
    artist: "Selena Gomez",
    type: "hollywood",
    album: "Calm Down(with Selena)",
  },
  {
    index: 10,
    name: "Without Me",
    source: "without_me",
    artist: "Eminem",
    type: "hollywood",
    album: "Without me (by Enimen)",
  },
  {
    index: 11,
    name: "Bad Guy",
    source: "bad_guy",
    artist: "Billie Eilish",
    type: "pop",
    album: "Bad Guy(by Billie Eilish)",
  },
  {
    index: 12,
    name: "WaterMelon Sugar",
    source: "Watermelon_sugar",
    artist: "Harry Styles",
    type: "pop",
    album: "Watermelon Sugar(byHarry Styles)",
  },
  {
    index: 13,
    name: "Stay",
    source: "Stay",
    artist: " Rihann",
    type: "pop",
    album: "Stay(by  Rihann)",
  },
  {
    index: 14,
    name: "Levitating",
    source: "Levitating",
    artist: "Dua Lipa",
    type: "pop",
    album: "Levitating(by Dua Lipa)",
  },
];

export default mediaData;
